language: go

go:
  - 1.4

env:
  - LIBWEBP_VERSION="0.4.1"
  - LIBWEBP_VERSION="0.4.2"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjpeg-dev libpng-dev libtiff-dev libgif-dev
  - >
      cd /tmp
      && wget http://downloads.webmproject.org/releases/webp/libwebp-${LIBWEBP_VERSION}.tar.gz
      && tar xf libwebp-${LIBWEBP_VERSION}.tar.gz
      && cd libwebp-${LIBWEBP_VERSION}
      && ./configure
      && make
      && sudo make install
  - cd $HOME/gopath/src/github.com/harukasan/go-libwebp
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
